language: php

node_js:
  - 7

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

install:
  - composer install
  - npm install
  - ./vendor/bin/simple-phpunit install

before_script:
  - node tests-js/json-rpc.js &

script:
  - ./vendor/bin/simple-phpunit -v
  - ./node_modules/.bin/mocha --require tests-js/bootstrap.js tests-js/twig/* tests-js/twig/*/*